application:
  domain: defcon.33
  name: 'DEF CON 33 Merch Store'
  logo: 'https://shop.defcon.org/cdn/shop/files/33-fullcolorgradient_1_720x.jpg?v=1740593533'
  favicon: 'https://defcon.org/images/favicon.ico'
  theme: lime-green
  showVersionNumber: false
  showGitHubLinks: false
  localBackupEnabled: true
  numberOfRandomFakeUsers: 42
  altcoinName: Defco(i)n
  privacyContactEmail: 'donotreply@defcon.33'
  customMetricsPrefix: defcon33
  chatBot:
    name: 'Conny'
    greeting: "Hi there, hacker known as <customer-name>! I'm <bot-name>, the friendly chatbot of DEF CON."
    defaultResponse: "Sorry, hacker! I couldn't reverse-engineer the meaning of your question."
    avatar: 'https://defcon.org/images/defcon-main/dc-forums.png'
  social:
    blueSkyUrl: 'https://bsky.app/profile/defcon.bsky.social'
    mastodonUrl: 'https://defcon.social/'
    twitterUrl: null
    facebookUrl: 'https://facebook.com/defcon'
    slackUrl: null
    redditUrl: 'https://www.reddit.com/r/defcon'
    pressKitUrl: 'https://media.defcon.org/'
    nftUrl: null
    questionnaireUrl: null
  welcomeBanner:
    showOnFirstStart: false
  cookieConsent:
    message: 'DEF CON wants to be up-front and transparent with what happens to the information that is gathered when you interact [1] with us.'
    dismissText: 'I trust you!'
    linkText: 'DEF CON Privacy Policy'
    linkUrl: 'https://defcon.org/html/links/dc-privacy.html'
ctf:
  showFlagsInNotifications: true
products:
  -
    name: 'DEFCON 32 Sticker Pack'
    price: 17
    description: "5 premium stickers: Glow in the Dark, Brushed Aluminium & Transparent"
    image: 'https://shop.defcon.org/cdn/shop/files/stickers_720x.jpg?v=1732936912'
  -
    name: 'Hawaiian Shirt'
    price: 60
    description: "DEFCON Hawaiian shirt! Soft and breezy. Perfect for a day at the pool."
    image: 'https://shop.defcon.org/cdn/shop/files/defcon-hawaiian_720x.png?v=1732927277'
  -
    name: 'DEFCON Holiday Sweater'
    price: 60
    description: "Get in to the DEFCON holiday spirit with our brand new knit sweaters! These sweaters are fully knitted with the design woven in. They are very soft and cozy – ideal for the stylish hacker in your life."
    image: 'https://shop.defcon.org/cdn/shop/files/y21QZGdI_720x.jpg?v=1732924318'
  -
    name: 'DEF CON 33 Las Vegas Convention Center'
    price: 540
    description: "DEF CON will always be a cash-at-the-door conference. We will always honor the LineCon. This is the way. Preregistration guarantees you'll receive a DEF CON 33 Human badge (as opposed to a paper badge, if we run out) when redeeming your ticket in Las Vegas. Badges must be picked up onsite."
    image: 'https://shop.defcon.org/cdn/shop/files/ticket_720x.jpg?v=1740606815'
    quantity: 3
  -
    name: 'Engage Hoodie - Lightweight Premium Zip Hoodie'
    description: 'An incredibly soft and relaxed unisex full zip up hoodie, spun from a plush poly-cotton blend, will quickly become a go-to essential. Features a relaxed fit, hood with white drawstrings, full zip closure and ribbed cuffs and waistband.'
    price: 55
    deluxePrice: 47
    image: 'https://shop.defcon.org/cdn/shop/files/ziphoodie_1080x.jpg?v=1732925354'
    urlForProductTamperingChallenge: 'https://shop.defcon.org/products/engage-hoodie-lightweight-premium-zip-hoodie'
  -
    name: 'DEF CON 32 Theme Pack'
    description: 'Contains all colors, fonts, styles and images for a fully immersed DEF CON 32 experience!'
    price: 99.99
    image: "https://media.defcon.org/DEF%20CON%2032/DEF%20CON%2032%20art/DEF%20CON%2032%20theme.webp"
    useForChristmasSpecialChallenge: true
  -
    name: 'Rippertuer Special Juice'
    description: 'Contains a magical collection of the rarest fruits gathered from all around the world, like Cherymoya Annona cherimola, Jabuticaba Myrciaria cauliflora, Bael Aegle marmelos... and others, at an unbelievable price! <br/><span style="color:red;">This item has been made unavailable because of lack of safety standards.</span>'
    price: 16.99
    image: undefined.jpg
    keywordsForPastebinDataLeakChallenge:
      - hueteroneel
      - eurogium edule
  -
    name: 'OWASP Juice Shop Logo (3D-printed)'
    description: 'This rare item was designed and handcrafted in Sweden. This is why it is so incredibly expensive despite its complete lack of purpose.'
    price: 99.99
    image: 3d_keychain.jpg # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
    exifForBlueprintChallenge:
      - OpenSCAD
